In [51]:
import numpy as np

In [16]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [19]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [26]:
a= np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
a = np.zeros((4,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
a = np.ones((4,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a = np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [33]:
a = np.arange(1,22,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [59]:
a1 = np.linspace(1,10,5)
a1

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [61]:
a = np.linspace(2,20,30)
a

array([ 2.        ,  2.62068966,  3.24137931,  3.86206897,  4.48275862,
        5.10344828,  5.72413793,  6.34482759,  6.96551724,  7.5862069 ,
        8.20689655,  8.82758621,  9.44827586, 10.06896552, 10.68965517,
       11.31034483, 11.93103448, 12.55172414, 13.17241379, 13.79310345,
       14.4137931 , 15.03448276, 15.65517241, 16.27586207, 16.89655172,
       17.51724138, 18.13793103, 18.75862069, 19.37931034, 20.        ])

In [62]:
a = np.full(3,3)
a

array([3, 3, 3])

In [66]:
a = np.full((5,4),10)
a

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [67]:
a = np.full((4,10),12)
a

array([[12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12]])

In [70]:
a = np.random.rand(3,3)
a

array([[0.31481795, 0.21751664, 0.73420645],
       [0.59321121, 0.60373592, 0.78059835],
       [0.05094634, 0.2860773 , 0.37329473]])

In [71]:
a = np.random.rand(5)
a

array([0.49020123, 0.6361357 , 0.39146576, 0.79670509, 0.10406992])

In [104]:
a = np.random.randint(5)
a

2

In [132]:
a = np.random.randint(3,10)
a

6

In [150]:
a = np.random.randint(3,10,10)
a

array([8, 5, 4, 9, 3, 7, 8, 8, 6, 4], dtype=int32)

In [151]:
a = np.random.randint(3,10,(3,3))
a

array([[8, 4, 8],
       [6, 7, 5],
       [9, 9, 8]], dtype=int32)