In [10]:
import numpy as np

In [ ]:
dir(np)

## Creating a array


In [7]:
l = [1, 4, 6, 8]
print(l)

[1, 4, 6, 8]


In [8]:
arr = np.array(l)
print(arr)

[1 4 6 8]


In [14]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
c = np.zeros(10)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
e = np.ones(5)
e

array([1., 1., 1., 1., 1.])

In [ ]:
f = np.eye(5)
f


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
c1 = np.zeros((4,5))
c1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
a1 = np.ones((4,5))
a1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
b2 = np.eye((4))
b2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
a4 = np.arange(1,11)
a4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
a5 = np.arange(1,10,2)
a5

array([1, 3, 5, 7, 9])

In [36]:
a6 = np.linspace(1,10,4)
a6

array([ 1.,  4.,  7., 10.])

In [37]:
a6 = np.full(5,3)
a6

array([3, 3, 3, 3, 3])

In [41]:
a6 = np.full((4,6),5)
a6

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [42]:
a5 = np.random.rand(3,4)
a5

array([[0.62822064, 0.18635875, 0.94066324, 0.77073028],
       [0.6277265 , 0.06594638, 0.46914134, 0.67707264],
       [0.57251466, 0.63584091, 0.9335627 , 0.54464135]])

In [43]:
a4 = np.random.rand(6)
a4

array([0.53880172, 0.14601485, 0.69999691, 0.43338859, 0.63663575,
       0.59932559])

In [48]:
a3 = np.random.randint(5)
a3


2

In [78]:
a4 = np.random.randint(4,10)
a4

8

In [86]:
a4 = np.random.randint(4,10,5)
a4

array([8, 9, 6, 6, 4], dtype=int32)

In [99]:
a4 = np.random.randint(4,10,(3,3))
a4

array([[6, 8, 5],
       [6, 7, 7],
       [4, 7, 6]], dtype=int32)

## Indexing of array

In [109]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
print(a[6])

7


In [114]:
print(a[-1])

9


In [123]:
a2 = np.random.randint(1,5,(3,3))
a2

array([[1, 4, 3],
       [3, 1, 1],
       [1, 4, 4]], dtype=int32)

In [125]:
print(a2[1][2])

1
